version: "3.8"

services:
  frontend:
    build:
      context: ./xpress-way
      dockerfile: ./Dockerfile
    ports:
      - "${FRONTEND_PORT}:80" # Map container port 80 to host port 5173
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "${BACKEND_PORT}:8002" # Map container port 8002 to host port 8002
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:  
      - MONGO_CONN_STR=${MONGO_CONN_STR}
      - MONGO_DB=${MONGO_DB}
      - PAYMENTS_URL="${PAYMENTS_URL}"
      - BACKEND_URL="${BACKEND_URL}"
      - FRONTEND_URL="${FRONTEND_URL}"
      - PAYMENTS_HOST="${PAYMENTS_HOST}"
      - PAYMENTS_PORT="${PAYMENTS_PORT}"
      - BACKEND_HOST="${BACKEND_HOST}"
      - BACKEND_PORT="${BACKEND_PORT}"
      - FRONTEND_HOST="${FRONTEND_HOST}"
      - FRONTEND_PORT="${FRONTEND_PORT}"
    networks:
      - app-network

  mongodb:
    image: mongo:8.0.9
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017" # Map container port 27017 to host port 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data: # Persistent storage for MongoDB

networks:
  app-network: