# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, payment_id: str=None, status: str=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param payment_id: The payment_id of this InlineResponse201.  # noqa: E501
        :type payment_id: str
        :param status: The status of this InlineResponse201.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'payment_id': str,
            'status': str
        }

        self.attribute_map = {
            'payment_id': 'payment_id',
            'status': 'status'
        }
        self._payment_id = payment_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payment_id(self) -> str:
        """Gets the payment_id of this InlineResponse201.


        :return: The payment_id of this InlineResponse201.
        :rtype: str
        """
        return self._payment_id

    @payment_id.setter
    def payment_id(self, payment_id: str):
        """Sets the payment_id of this InlineResponse201.


        :param payment_id: The payment_id of this InlineResponse201.
        :type payment_id: str
        """

        self._payment_id = payment_id

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse201.


        :return: The status of this InlineResponse201.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse201.


        :param status: The status of this InlineResponse201.
        :type status: str
        """

        self._status = status
