# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V1PaymentsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: int=None, currency: str=None):  # noqa: E501
        """V1PaymentsBody - a model defined in Swagger

        :param amount: The amount of this V1PaymentsBody.  # noqa: E501
        :type amount: int
        :param currency: The currency of this V1PaymentsBody.  # noqa: E501
        :type currency: str
        """
        self.swagger_types = {
            'amount': int,
            'currency': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'currency': 'currency'
        }
        self._amount = amount
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'V1PaymentsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1_payments_body of this V1PaymentsBody.  # noqa: E501
        :rtype: V1PaymentsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> int:
        """Gets the amount of this V1PaymentsBody.


        :return: The amount of this V1PaymentsBody.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this V1PaymentsBody.


        :param amount: The amount of this V1PaymentsBody.
        :type amount: int
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def currency(self) -> str:
        """Gets the currency of this V1PaymentsBody.


        :return: The currency of this V1PaymentsBody.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this V1PaymentsBody.


        :param currency: The currency of this V1PaymentsBody.
        :type currency: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501

        self._currency = currency
