openapi: 3.0.0
info:
  title: XpressWay
  description: Simple payment API for processing guest checkout transactions
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/SamuTheCoder/XpressWay/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:3000
paths:
  /v1/payments:
    post:
      summary: Create a new payment
      description: Initializes a payment and returns a payment ID with pending status.
      operationId: v1_payments_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_payments_body'
        required: true
      responses:
        "201":
          description: Payment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Invalid request parameters
        "500":
          description: Server error
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    v1_payments_body:
      required:
      - amount
      - currency
      type: object
      properties:
        amount:
          type: integer
          example: 5000
        currency:
          type: string
          example: USD
    inline_response_201:
      type: object
      properties:
        payment_id:
          type: string
          example: pay_123456
        status:
          type: string
          example: pending
      example:
        payment_id: pay_123456
        status: pending

