# coding: utf-8

"""
    XpressWay

    Simple payment API for processing guest checkout transactions  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1_payments_body import V1PaymentsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestV1PaymentsBody(unittest.TestCase):
    """V1PaymentsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PaymentsBody(self):
        """Test V1PaymentsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_payments_body.V1PaymentsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
