# coding: utf-8

"""
    XpressWay

    Simple payment API for processing guest checkout transactions  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_payments_post(self):
        """Test case for v1_payments_post

        Create a new payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
